### ISSUE TITLE
spacy not working

### ISSUE THREAD

**Issue by dietrichmd** [com1234475/stash-plugin-performer-creator#8]
Using stash inside docker.

When trying to search for performers, the log shows this error:

```
22-01-09 09:22:27
Error   
Plugin returned error: exit status 1
2022-01-09 09:22:27
Error   
[Plugin / Performer Creator] ModuleNotFoundError: No module named 'spacy'
2022-01-09 09:22:27
Error   
[Plugin / Performer Creator]     import spacy
2022-01-09 09:22:27
Error   
[Plugin / Performer Creator]   File "/root/.stash/plugins/performer_creator.py", line 13, in <module>
2022-01-09 09:22:27
Error   
[Plugin / Performer Creator] Traceback (most recent call last):
```

Any ideas?

**Comment by IntoTheBlackHole** [comment]
> Using stash inside docker.
> 
> Installed plugin using following instructions:
> 
> ```
> Add the python files too your .stash/plugins directory
> 
> create a virtualenv
> 
> virtualenv -p python3 --system-site-packages ~/.stash/plugins/env
> source ~/.stash/plugins/env/bin/activate
> pip install ~/.stash/plugins/requirements.txt
> python -m spacy download en_core_web_md
> ```
> 
> That said, I cant get virtualenv to run inside docker shell, so running it using the /home/stash/config/plugins/* instead.
> 
> When trying to search for performers, the log shows this error:
> 
> ```
> 22-01-09 09:22:27
> Error   
> Plugin returned error: exit status 1
> 2022-01-09 09:22:27
> Error   
> [Plugin / Performer Creator] ModuleNotFoundError: No module named 'spacy'
> 2022-01-09 09:22:27
> Error   
> [Plugin / Performer Creator]     import spacy
> 2022-01-09 09:22:27
> Error   
> [Plugin / Performer Creator]   File "/root/.stash/plugins/performer_creator.py", line 13, in <module>
> 2022-01-09 09:22:27
> Error   
> [Plugin / Performer Creator] Traceback (most recent call last):
> ```
> 
> Any ideas?

run this and then try installing spacy. worked for me.
`pip3 install --upgrade setuptools`
`python -m spacy download en_core_web_md`
